name: rumblr
description: A Flutter app for MMA fighters to rank in an ELO system, find gyms, book classes, host tournaments, and connect in communities.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: 5.6.1
  cloud_firestore: ^5.4.4  # Added for Firestore features
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  firebase_messaging: ^15.2.8
  flutter_local_notifications: ^17.2.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tasks.json
