// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKsPHi7B_WkqdKZgTSXYovZPYdbspcnYw',
    appId: '1:940423942426:web:b1a6bd8748b8047d489ca3',
    messagingSenderId: '940423942426',
    projectId: 'rumblr-f8c63',
    authDomain: 'rumblr-f8c63.firebaseapp.com',
    storageBucket: 'rumblr-f8c63.firebasestorage.app',
    measurementId: 'G-1GV57Q785R',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4w1uCSqIwzg0eH5LpfgHXhvvJKEUtxyo',
    appId: '1:940423942426:ios:37e7320bfad249a3489ca3',
    messagingSenderId: '940423942426',
    projectId: 'rumblr-f8c63',
    storageBucket: 'rumblr-f8c63.firebasestorage.app',
    iosBundleId: 'com.example.rumblr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4w1uCSqIwzg0eH5LpfgHXhvvJKEUtxyo',
    appId: '1:940423942426:ios:37e7320bfad249a3489ca3',
    messagingSenderId: '940423942426',
    projectId: 'rumblr-f8c63',
    storageBucket: 'rumblr-f8c63.firebasestorage.app',
    iosBundleId: 'com.example.rumblr',
  );

}